apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwpulsar-deployment
  labels:
    app: gwpulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gwpulsar
  template:
    metadata:
      labels:
        app: gwpulsar
    spec:
      containers:
      - name: pulsar-exp
        image: fracasula/gwpulsar:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PULSAR_URL
          value: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: TOPIC_NAME
          value: "persistent://public/fcasula/gwpulsar-test"
        - name: BATCH_MAX_DELAY
          value: "10ms"
        - name: BATCH_MAX_MESSAGES
          value: "1000"
        - name: MAX_CONNECTIONS_PER_BROKER
          value: "20"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gwpulsar-svc
  labels:
    app: gwpulsar
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gwpulsar
